### ISSUE TITLE
Error: com.currencyfair.onesignal.OneSignalException: app_id not found. You may be missing a Content-Type: application/json header.

### ISSUE THREAD

**Issue by ceefour** [CurrencyFair/OneSignal-Java-SDK#12]
createNotification() doesn't work. Pretty sure I gave the right "REST API Key" for my project.

```
com.currencyfair.onesignal.OneSignalException: app_id not found. You may be missing a Content-Type: application/json header.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingConstructorAccessorImpl.__newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_144]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java) ~[na:1.8.0_144]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java) ~[na:1.8.0_144]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_144]
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:119) ~[jackson-databind-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDefault(StdValueInstantiator.java:260) ~[jackson-databind-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:145) ~[jackson-databind-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148) ~[jackson-databind-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814) ~[jackson-databind-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2917) ~[jackson-databind-2.8.10.jar:2.8.10]
	at feign.jackson.JacksonDecoder.decode(JacksonDecoder.java:65) ~[feign-jackson-9.4.0.jar:na]
	at com.currencyfair.onesignal.OneSignalErrorDecoder.decode(OneSignalErrorDecoder.java:39) ~[onesignal-1.0.9.jar:na]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138) ~[feign-core-9.4.0.jar:na]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76) ~[feign-core-9.4.0.jar:na]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103) ~[feign-core-9.4.0.jar:na]
	at com.sun.proxy.$Proxy220.createNotification(Unknown Source) ~[na:na]
	at com.currencyfair.onesignal.OneSignal.createNotification(OneSignal.java:71) ~[onesignal-1.0.9.jar:na]
```

**Comment by ceefour** [comment]
Sorry, my bad. Needed `.withAppId()`
